### ISSUE TITLE
redbpf-iotop panics with 'cannot attach kprobe, probe entry may not exist' when attaching kprobe for 'blk_start_request'

### ISSUE THREAD

**Issue by wfchandler** [redsift/redbpf#85]
When running `redbpf-iotop` as root, the program panics immediately.  I'm running on Fedora 32, and my kernel was built with `CONFIG_KPROBE_EVENTS=y`.

```sh
$ uname -a
Linux localhost.localdomain 5.8.9-200.fc32.x86_64 #1 SMP Mon Sep 14 18:28:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
```

Based on the `strace` output below, attempting to enable tracing for `kprobes/blk_start_request` is triggering the error.  [This article from Brendan Gregg](https://www.informit.com/articles/article.aspx?p=2995360&seqNum=3) mentions that `blk_start_request` was removed in Linux 5.0:

> With the Linux 5.0 switch to multi-queue only, the blk_start_request() function was removed from the kernel. 

#### Backtrace

```rust
sudo RUST_BACKTRACE=1 target/debug/redbpf-iotop
cannot attach kprobe, probe entry may not exist
thread 'main' panicked at 'error attaching program blk_start_request: BPF', redbpf-tools/src/bin/redbpf-iotop.rs:31:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: core::result::Result<T,E>::expect
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:963
  15: redbpf_iotop::main::{{closure}}
             at redbpf-tools/src/bin/redbpf-iotop.rs:29
```

#### Relevant strace output

```
02:12:23.264516 openat(AT_FDCWD, "/sys/bus/event_source/devices/kprobe/type", O_RDONLY) = 13</sys/devices/kprobe/type> <0.000093>
02:12:23.264837 read(13</sys/devices/kprobe/type>, "6\n", 4096) = 2 <0.000107>
02:12:23.265112 close(13</sys/devices/kprobe/type>) = 0 <0.000100>
02:12:23.265371 openat(AT_FDCWD, "/sys/bus/event_source/devices/kprobe/format/retprobe", O_RDONLY) = 13</sys/devices/kprobe/format/retprobe> <0.000107>
02:12:23.265626 read(13</sys/devices/kprobe/format/retprobe>, "config:0\n", 4096) = 9 <0.000095>
02:12:23.265883 close(13</sys/devices/kprobe/format/retprobe>) = 0 <0.000104>
02:12:23.266133 perf_event_open({type=0x6 /* PERF_TYPE_??? */, size=PERF_ATTR_SIZE_VER6, config=0, ...}, -1, 0, -1, PERF_FLAG_FD_CLOEXEC) = 13<anon_inode:[perf_event]> <0.008230>
02:12:23.274672 ioctl(13<anon_inode:[perf_event]>, PERF_EVENT_IOC_SET_BPF, 9<anon_inode:bpf-prog>) = 0 <0.000165>
02:12:23.275063 ioctl(13<anon_inode:[perf_event]>, PERF_EVENT_IOC_ENABLE, 0) = 0 <0.000199>
02:12:23.275546 openat(AT_FDCWD, "/sys/bus/event_source/devices/kprobe/type", O_RDONLY) = 14</sys/devices/kprobe/type> <0.000242>
02:12:23.276083 read(14</sys/devices/kprobe/type>, "6\n", 4096) = 2 <0.000145>
02:12:23.276503 close(14</sys/devices/kprobe/type>) = 0 <0.000208>
02:12:23.276971 openat(AT_FDCWD, "/sys/bus/event_source/devices/kprobe/format/retprobe", O_RDONLY) = 14</sys/devices/kprobe/format/retprobe> <0.000174>
02:12:23.277400 read(14</sys/devices/kprobe/format/retprobe>, "config:0\n", 4096) = 9 <0.000154>
02:12:23.277780 close(14</sys/devices/kprobe/format/retprobe>) = 0 <0.000126>
02:12:23.278176 perf_event_open({type=0x6 /* PERF_TYPE_??? */, size=PERF_ATTR_SIZE_VER6, config=0, ...}, -1, 0, -1, PERF_FLAG_FD_CLOEXEC) = -1 ENOENT (No such file or directory) <0.025770>
02:12:23.304218 openat(AT_FDCWD, "/sys/kernel/debug/tracing/kprobe_events", O_WRONLY|O_APPEND) = 14</sys/kernel/debug/tracing/kprobe_events> <0.000159>
02:12:23.304679 getpid()                = 29020 <0.000215>
02:12:23.305126 write(14</sys/kernel/debug/tracing/kprobe_events>, "p:kprobes/blk_start_request0_bcc_29020 blk_start_request", 56) = -1 ENOENT (No such file or directory) <0.035550>
02:12:23.340915 write(2</dev/pts/2<char 136:2>>, "cannot attach kprobe, probe entry may not exist\n", 48cannot attach kprobe, probe entry may not exist
) = 48 <0.000126>
02:12:23.341287 close(14</sys/kernel/debug/tracing/kprobe_events>) = 0 <0.000174>
02:12:23.341738 write(2</dev/pts/2<char 136:2>>, "thread '", 8thread ') = 8 <0.000123>
02:12:23.342176 write(2</dev/pts/2<char 136:2>>, "main", 4main) = 4 <0.000123>
02:12:23.342510 write(2</dev/pts/2<char 136:2>>, "' panicked at '", 15' panicked at ') = 15 <0.000145>
02:12:23.342864 write(2</dev/pts/2<char 136:2>>, "error attaching program blk_start_request: BPF", 46error attaching program blk_start_request: BPF) = 46 <0.000124>
```

**Comment by rsdy** [comment]
Thanks for the detailed issue. I pushed a fix for the iotop example that fixes this!
